BoxLayout:
    orientation: 'horizontal'
    id: main
    BoxLayout:
        orientation: 'vertical'
        id: specieslabs
        Label:
            size_hint_y: 0.1
            text: "Species:"
            color: (0, 1, 1, 1)
            font_size: 24

    BoxLayout:
        orientation: 'vertical'
        id: dietlabs
        Label:
            size_hint_y: 0.1
            text: "Diet:"
            font_size: 24
            color: (1, 1, 0, 1)